simulation_name: my_super_tutorial_example
constellation_file: configurations/constellation_25_25.txt
ground_station_file: configurations/ground_stations.txt
ground_station_link_range: 200000 # 1000 km range
start_date: 01/01/2024 10:00:00
end_date: 01/02/2024 10:00:00
movement_model: pyorbital
distance_model: geopy
disable_ground_station_link_preload: False